export const site = {
  name: "Sheila Kwan",
  legalName: "Sheila Kwan Consulting",
  tagline: "AI implementation, customer success, and pipeline systems for B2B teams",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://sheilakwan.com",
  email: "hello@sheilakwan.com",
  linkedin: "https://linkedin.com/in/sheila-kwan",
  location: "Greater Toronto Area, Canada. Serving North America remotely.",
  mailingAddress: "Toronto, Ontario, Canada",
  calLink: process.env.NEXT_PUBLIC_CAL_LINK?.trim() ?? "",
  yearsInRevenue: "a decade",
  foundingSlotsRemaining: 3,
  currency: "USD",
  prices: {
    audit: "$4,500",
    auditFounding: "$3,500",
    sprint: "$9,500",
    csBuild: "$12,000",
    fractional: "$5,000 / month",
    pipelineBuild: "$8,500",
    pipelineRun: "$2,500 / month",
    advisory: "$2,000 / month",
  },
} as const;
